(function(modules){var installedModules={};function __webpack_require__(moduleId){if(installedModules[moduleId])
return installedModules[moduleId].exports;var module=installedModules[moduleId]={exports:{},id:moduleId,loaded:false};modules[moduleId].call(module.exports,module,module.exports,__webpack_require__);module.loaded=true;return module.exports;}
__webpack_require__.m=modules;__webpack_require__.c=installedModules;__webpack_require__.p="";return __webpack_require__(0);})([function(module,exports,__webpack_require__){'use strict';__webpack_require__(8);__webpack_require__(9);__webpack_require__(10);},,,,,,,,function(module,exports){;(function(window,document,undefined){var tests=[];var ModernizrProto={_version:'3.3.1',_config:{'classPrefix':'','enableClasses':true,'enableJSClass':true,'usePrefixes':true},_q:[],on:function(test,cb){var self=this;setTimeout(function(){cb(self[test]);},0);},addTest:function(name,fn,options){tests.push({name:name,fn:fn,options:options});},addAsyncTest:function(fn){tests.push({name:null,fn:fn});}};var Modernizr=function(){};Modernizr.prototype=ModernizrProto;Modernizr=new Modernizr();var classes=[];function is(obj,type){return typeof obj===type;};function testRunner(){var featureNames;var feature;var aliasIdx;var result;var nameIdx;var featureName;var featureNameSplit;for(var featureIdx in tests){if(tests.hasOwnProperty(featureIdx)){featureNames=[];feature=tests[featureIdx];if(feature.name){featureNames.push(feature.name.toLowerCase());if(feature.options&&feature.options.aliases&&feature.options.aliases.length){for(aliasIdx=0;aliasIdx<feature.options.aliases.length;aliasIdx++){featureNames.push(feature.options.aliases[aliasIdx].toLowerCase());}}}
result=is(feature.fn,'function')?feature.fn():feature.fn;for(nameIdx=0;nameIdx<featureNames.length;nameIdx++){featureName=featureNames[nameIdx];featureNameSplit=featureName.split('.');if(featureNameSplit.length===1){Modernizr[featureNameSplit[0]]=result;}else{if(Modernizr[featureNameSplit[0]]&&!(Modernizr[featureNameSplit[0]]instanceof Boolean)){Modernizr[featureNameSplit[0]]=new Boolean(Modernizr[featureNameSplit[0]]);}
Modernizr[featureNameSplit[0]][featureNameSplit[1]]=result;}
classes.push((result?'':'no-')+featureNameSplit.join('-'));}}}};var docElement=document.documentElement;var isSVG=docElement.nodeName.toLowerCase()==='svg';function setClasses(classes){var className=docElement.className;var classPrefix=Modernizr._config.classPrefix||'';if(isSVG){className=className.baseVal;}
if(Modernizr._config.enableJSClass){var reJS=new RegExp('(^|\\s)'+classPrefix+'no-js(\\s|$)');className=className.replace(reJS,'$1'+classPrefix+'js$2');}
if(Modernizr._config.enableClasses){className+=' '+classPrefix+classes.join(' '+classPrefix);isSVG?docElement.className.baseVal=className:docElement.className=className;}};var omPrefixes='Moz O ms Webkit';var cssomPrefixes=(ModernizrProto._config.usePrefixes?omPrefixes.split(' '):[]);ModernizrProto._cssomPrefixes=cssomPrefixes;function contains(str,substr){return!!~(''+str).indexOf(substr);};function createElement(){if(typeof document.createElement!=='function'){return document.createElement(arguments[0]);}else if(isSVG){return document.createElementNS.call(document,'http://www.w3.org/2000/svg',arguments[0]);}else{return document.createElement.apply(document,arguments);}};var modElem={elem:createElement('modernizr')};Modernizr._q.push(function(){delete modElem.elem;});var mStyle={style:modElem.elem.style};Modernizr._q.unshift(function(){delete mStyle.style;});function getBody(){var body=document.body;if(!body){body=createElement(isSVG?'svg':'body');body.fake=true;}
return body;};function injectElementWithStyles(rule,callback,nodes,testnames){var mod='modernizr';var style;var ret;var node;var docOverflow;var div=createElement('div');var body=getBody();if(parseInt(nodes,10)){while(nodes--){node=createElement('div');node.id=testnames?testnames[nodes]:mod+(nodes+1);div.appendChild(node);}}
style=createElement('style');style.type='text/css';style.id='s'+mod;(!body.fake?div:body).appendChild(style);body.appendChild(div);if(style.styleSheet){style.styleSheet.cssText=rule;}else{style.appendChild(document.createTextNode(rule));}
div.id=mod;if(body.fake){body.style.background='';body.style.overflow='hidden';docOverflow=docElement.style.overflow;docElement.style.overflow='hidden';docElement.appendChild(body);}
ret=callback(div,rule);if(body.fake){body.parentNode.removeChild(body);docElement.style.overflow=docOverflow;docElement.offsetHeight;}else{div.parentNode.removeChild(div);}
return!!ret;};function domToCSS(name){return name.replace(/([A-Z])/g,function(str,m1){return'-'+m1.toLowerCase();}).replace(/^ms-/,'-ms-');};function nativeTestProps(props,value){var i=props.length;if('CSS'in window&&'supports'in window.CSS){while(i--){if(window.CSS.supports(domToCSS(props[i]),value)){return true;}}
return false;}
else if('CSSSupportsRule'in window){var conditionText=[];while(i--){conditionText.push('('+domToCSS(props[i])+':'+value+')');}
conditionText=conditionText.join(' or ');return injectElementWithStyles('@supports ('+conditionText+') { #modernizr { position: absolute; } }',function(node){return getComputedStyle(node,null).position=='absolute';});}
return undefined;};function cssToDOM(name){return name.replace(/([a-z])-([a-z])/g,function(str,m1,m2){return m1+m2.toUpperCase();}).replace(/^-/,'');};function testProps(props,prefixed,value,skipValueTest){skipValueTest=is(skipValueTest,'undefined')?false:skipValueTest;if(!is(value,'undefined')){var result=nativeTestProps(props,value);if(!is(result,'undefined')){return result;}}
var afterInit,i,propsLength,prop,before;var elems=['modernizr','tspan'];while(!mStyle.style){afterInit=true;mStyle.modElem=createElement(elems.shift());mStyle.style=mStyle.modElem.style;}
function cleanElems(){if(afterInit){delete mStyle.style;delete mStyle.modElem;}}
propsLength=props.length;for(i=0;i<propsLength;i++){prop=props[i];before=mStyle.style[prop];if(contains(prop,'-')){prop=cssToDOM(prop);}
if(mStyle.style[prop]!==undefined){if(!skipValueTest&&!is(value,'undefined')){try{mStyle.style[prop]=value;}catch(e){}
if(mStyle.style[prop]!=before){cleanElems();return prefixed=='pfx'?prop:true;}}
else{cleanElems();return prefixed=='pfx'?prop:true;}}}
cleanElems();return false;};var domPrefixes=(ModernizrProto._config.usePrefixes?omPrefixes.toLowerCase().split(' '):[]);ModernizrProto._domPrefixes=domPrefixes;function fnBind(fn,that){return function(){return fn.apply(that,arguments);};};function testDOMProps(props,obj,elem){var item;for(var i in props){if(props[i]in obj){if(elem===false){return props[i];}
item=obj[props[i]];if(is(item,'function')){return fnBind(item,elem||obj);}
return item;}}
return false;};function testPropsAll(prop,prefixed,elem,value,skipValueTest){var ucProp=prop.charAt(0).toUpperCase()+prop.slice(1),props=(prop+' '+cssomPrefixes.join(ucProp+' ')+ucProp).split(' ');if(is(prefixed,'string')||is(prefixed,'undefined')){return testProps(props,prefixed,value,skipValueTest);}else{props=(prop+' '+(domPrefixes).join(ucProp+' ')+ucProp).split(' ');return testDOMProps(props,prefixed,elem);}}
ModernizrProto.testAllProps=testPropsAll;function testAllProps(prop,value,skipValueTest){return testPropsAll(prop,undefined,undefined,value,skipValueTest);}
ModernizrProto.testAllProps=testAllProps;Modernizr.addTest('flexbox',testAllProps('flexBasis','1px',true));Modernizr.addTest('svg',!!document.createElementNS&&!!document.createElementNS('http://www.w3.org/2000/svg','svg').createSVGRect);testRunner();setClasses(classes);delete ModernizrProto.addTest;delete ModernizrProto.addAsyncTest;for(var i=0;i<Modernizr._q.length;i++){Modernizr._q[i]();}
window.Modernizr=Modernizr;;})(window,document);},function(module,exports,__webpack_require__){var __WEBPACK_AMD_DEFINE_RESULT__;(function(window){var ua=navigator.userAgent;if(window.HTMLPictureElement&&((/ecko/).test(ua)&&ua.match(/rv\:(\d+)/)&&RegExp.$1<45)){addEventListener("resize",(function(){var timer;var dummySrc=document.createElement("source");var fixRespimg=function(img){var source,sizes;var picture=img.parentNode;if(picture.nodeName.toUpperCase()==="PICTURE"){source=dummySrc.cloneNode();picture.insertBefore(source,picture.firstElementChild);setTimeout(function(){picture.removeChild(source);});}else if(!img._pfLastSize||img.offsetWidth>img._pfLastSize){img._pfLastSize=img.offsetWidth;sizes=img.sizes;img.sizes+=",100vw";setTimeout(function(){img.sizes=sizes;});}};var findPictureImgs=function(){var i;var imgs=document.querySelectorAll("picture > img, img[srcset][sizes]");for(i=0;i<imgs.length;i++){fixRespimg(imgs[i]);}};var onResize=function(){clearTimeout(timer);timer=setTimeout(findPictureImgs,99);};var mq=window.matchMedia&&matchMedia("(orientation: landscape)");var init=function(){onResize();if(mq&&mq.addListener){mq.addListener(onResize);}};dummySrc.srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";if(/^[c|i]|d$/.test(document.readyState||"")){init();}else{document.addEventListener("DOMContentLoaded",init);}
return onResize;})());}})(window);(function(window,document,undefined){"use strict";document.createElement("picture");var warn,eminpx,alwaysCheckWDescriptor,evalId;var pf={};var isSupportTestReady=false;var noop=function(){};var image=document.createElement("img");var getImgAttr=image.getAttribute;var setImgAttr=image.setAttribute;var removeImgAttr=image.removeAttribute;var docElem=document.documentElement;var types={};var cfg={algorithm:""};var srcAttr="data-pfsrc";var srcsetAttr=srcAttr+"set";var ua=navigator.userAgent;var supportAbort=(/rident/).test(ua)||((/ecko/).test(ua)&&ua.match(/rv\:(\d+)/)&&RegExp.$1>35);var curSrcProp="currentSrc";var regWDesc=/\s+\+?\d+(e\d+)?w/;var regSize=/(\([^)]+\))?\s*(.+)/;var setOptions=window.picturefillCFG;var baseStyle="position:absolute;left:0;visibility:hidden;display:block;padding:0;border:none;font-size:1em;width:1em;overflow:hidden;clip:rect(0px, 0px, 0px, 0px)";var fsCss="font-size:100%!important;";var isVwDirty=true;var cssCache={};var sizeLengthCache={};var DPR=window.devicePixelRatio;var units={px:1,"in":96};var anchor=document.createElement("a");var alreadyRun=false;var regexLeadingSpaces=/^[ \t\n\r\u000c]+/,regexLeadingCommasOrSpaces=/^[, \t\n\r\u000c]+/,regexLeadingNotSpaces=/^[^ \t\n\r\u000c]+/,regexTrailingCommas=/[,]+$/,regexNonNegativeInteger=/^\d+$/,regexFloatingPoint=/^-?(?:[0-9]+|[0-9]*\.[0-9]+)(?:[eE][+-]?[0-9]+)?$/;var on=function(obj,evt,fn,capture){if(obj.addEventListener){obj.addEventListener(evt,fn,capture||false);}else if(obj.attachEvent){obj.attachEvent("on"+evt,fn);}};var memoize=function(fn){var cache={};return function(input){if(!(input in cache)){cache[input]=fn(input);}
return cache[input];};};function isSpace(c){return(c==="\u0020"||c==="\u0009"||c==="\u000A"||c==="\u000C"||c==="\u000D");}
var evalCSS=(function(){var regLength=/^([\d\.]+)(em|vw|px)$/;var replace=function(){var args=arguments,index=0,string=args[0];while(++index in args){string=string.replace(args[index],args[++index]);}
return string;};var buildStr=memoize(function(css){return"return "+replace((css||"").toLowerCase(),/\band\b/g,"&&",/,/g,"||",/min-([a-z-\s]+):/g,"e.$1>=",/max-([a-z-\s]+):/g,"e.$1<=",/calc([^)]+)/g,"($1)",/(\d+[\.]*[\d]*)([a-z]+)/g,"($1 * e.$2)",/^(?!(e.[a-z]|[0-9\.&=|><\+\-\*\(\)\/])).*/ig,"")+";";});return function(css,length){var parsedLength;if(!(css in cssCache)){cssCache[css]=false;if(length&&(parsedLength=css.match(regLength))){cssCache[css]=parsedLength[1]*units[parsedLength[2]];}else{try{cssCache[css]=new Function("e",buildStr(css))(units);}catch(e){}}}
return cssCache[css];};})();var setResolution=function(candidate,sizesattr){if(candidate.w){candidate.cWidth=pf.calcListLength(sizesattr||"100vw");candidate.res=candidate.w/candidate.cWidth;}else{candidate.res=candidate.d;}
return candidate;};var picturefill=function(opt){if(!isSupportTestReady){return;}
var elements,i,plen;var options=opt||{};if(options.elements&&options.elements.nodeType===1){if(options.elements.nodeName.toUpperCase()==="IMG"){options.elements=[options.elements];}else{options.context=options.elements;options.elements=null;}}
elements=options.elements||pf.qsa((options.context||document),(options.reevaluate||options.reselect)?pf.sel:pf.selShort);if((plen=elements.length)){pf.setupRun(options);alreadyRun=true;for(i=0;i<plen;i++){pf.fillImg(elements[i],options);}
pf.teardownRun(options);}};warn=(window.console&&console.warn)?function(message){console.warn(message);}:noop;if(!(curSrcProp in image)){curSrcProp="src";}
types["image/jpeg"]=true;types["image/gif"]=true;types["image/png"]=true;function detectTypeSupport(type,typeUri){var image=new window.Image();image.onerror=function(){types[type]=false;picturefill();};image.onload=function(){types[type]=image.width===1;picturefill();};image.src=typeUri;return"pending";}
types["image/svg+xml"]=document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1");function updateMetrics(){isVwDirty=false;DPR=window.devicePixelRatio;cssCache={};sizeLengthCache={};pf.DPR=DPR||1;units.width=Math.max(window.innerWidth||0,docElem.clientWidth);units.height=Math.max(window.innerHeight||0,docElem.clientHeight);units.vw=units.width/100;units.vh=units.height/100;evalId=[units.height,units.width,DPR].join("-");units.em=pf.getEmValue();units.rem=units.em;}
function chooseLowRes(lowerValue,higherValue,dprValue,isCached){var bonusFactor,tooMuch,bonus,meanDensity;if(cfg.algorithm==="saveData"){if(lowerValue>2.7){meanDensity=dprValue+1;}else{tooMuch=higherValue-dprValue;bonusFactor=Math.pow(lowerValue-0.6,1.5);bonus=tooMuch*bonusFactor;if(isCached){bonus+=0.1*bonusFactor;}
meanDensity=lowerValue+bonus;}}else{meanDensity=(dprValue>1)?Math.sqrt(lowerValue*higherValue):lowerValue;}
return meanDensity>dprValue;}
function applyBestCandidate(img){var srcSetCandidates;var matchingSet=pf.getSet(img);var evaluated=false;if(matchingSet!=="pending"){evaluated=evalId;if(matchingSet){srcSetCandidates=pf.setRes(matchingSet);pf.applySetCandidate(srcSetCandidates,img);}}
img[pf.ns].evaled=evaluated;}
function ascendingSort(a,b){return a.res-b.res;}
function setSrcToCur(img,src,set){var candidate;if(!set&&src){set=img[pf.ns].sets;set=set&&set[set.length-1];}
candidate=getCandidateForSrc(src,set);if(candidate){src=pf.makeUrl(src);img[pf.ns].curSrc=src;img[pf.ns].curCan=candidate;if(!candidate.res){setResolution(candidate,candidate.set.sizes);}}
return candidate;}
function getCandidateForSrc(src,set){var i,candidate,candidates;if(src&&set){candidates=pf.parseSet(set);src=pf.makeUrl(src);for(i=0;i<candidates.length;i++){if(src===pf.makeUrl(candidates[i].url)){candidate=candidates[i];break;}}}
return candidate;}
function getAllSourceElements(picture,candidates){var i,len,source,srcset;var sources=picture.getElementsByTagName("source");for(i=0,len=sources.length;i<len;i++){source=sources[i];source[pf.ns]=true;srcset=source.getAttribute("srcset");if(srcset){candidates.push({srcset:srcset,media:source.getAttribute("media"),type:source.getAttribute("type"),sizes:source.getAttribute("sizes")});}}}
function parseSrcset(input,set){function collectCharacters(regEx){var chars,match=regEx.exec(input.substring(pos));if(match){chars=match[0];pos+=chars.length;return chars;}}
var inputLength=input.length,url,descriptors,currentDescriptor,state,c,pos=0,candidates=[];function parseDescriptors(){var pError=false,w,d,h,i,candidate={},desc,lastChar,value,intVal,floatVal;for(i=0;i<descriptors.length;i++){desc=descriptors[i];lastChar=desc[desc.length-1];value=desc.substring(0,desc.length-1);intVal=parseInt(value,10);floatVal=parseFloat(value);if(regexNonNegativeInteger.test(value)&&(lastChar==="w")){if(w||d){pError=true;}
if(intVal===0){pError=true;}else{w=intVal;}}else if(regexFloatingPoint.test(value)&&(lastChar==="x")){if(w||d||h){pError=true;}
if(floatVal<0){pError=true;}else{d=floatVal;}}else if(regexNonNegativeInteger.test(value)&&(lastChar==="h")){if(h||d){pError=true;}
if(intVal===0){pError=true;}else{h=intVal;}}else{pError=true;}}
if(!pError){candidate.url=url;if(w){candidate.w=w;}
if(d){candidate.d=d;}
if(h){candidate.h=h;}
if(!h&&!d&&!w){candidate.d=1;}
if(candidate.d===1){set.has1x=true;}
candidate.set=set;candidates.push(candidate);}}
function tokenize(){collectCharacters(regexLeadingSpaces);currentDescriptor="";state="in descriptor";while(true){c=input.charAt(pos);if(state==="in descriptor"){if(isSpace(c)){if(currentDescriptor){descriptors.push(currentDescriptor);currentDescriptor="";state="after descriptor";}}else if(c===","){pos+=1;if(currentDescriptor){descriptors.push(currentDescriptor);}
parseDescriptors();return;}else if(c==="\u0028"){currentDescriptor=currentDescriptor+c;state="in parens";}else if(c===""){if(currentDescriptor){descriptors.push(currentDescriptor);}
parseDescriptors();return;}else{currentDescriptor=currentDescriptor+c;}}else if(state==="in parens"){if(c===")"){currentDescriptor=currentDescriptor+c;state="in descriptor";}else if(c===""){descriptors.push(currentDescriptor);parseDescriptors();return;}else{currentDescriptor=currentDescriptor+c;}}else if(state==="after descriptor"){if(isSpace(c)){}else if(c===""){parseDescriptors();return;}else{state="in descriptor";pos-=1;}}
pos+=1;}}
while(true){collectCharacters(regexLeadingCommasOrSpaces);if(pos>=inputLength){return candidates;}
url=collectCharacters(regexLeadingNotSpaces);descriptors=[];if(url.slice(-1)===","){url=url.replace(regexTrailingCommas,"");parseDescriptors();}else{tokenize();}}}
function parseSizes(strValue){var regexCssLengthWithUnits=/^(?:[+-]?[0-9]+|[0-9]*\.[0-9]+)(?:[eE][+-]?[0-9]+)?(?:ch|cm|em|ex|in|mm|pc|pt|px|rem|vh|vmin|vmax|vw)$/i;var regexCssCalc=/^calc\((?:[0-9a-z \.\+\-\*\/\(\)]+)\)$/i;var i;var unparsedSizesList;var unparsedSizesListLength;var unparsedSize;var lastComponentValue;var size;function parseComponentValues(str){var chrctr;var component="";var componentArray=[];var listArray=[];var parenDepth=0;var pos=0;var inComment=false;function pushComponent(){if(component){componentArray.push(component);component="";}}
function pushComponentArray(){if(componentArray[0]){listArray.push(componentArray);componentArray=[];}}
while(true){chrctr=str.charAt(pos);if(chrctr===""){pushComponent();pushComponentArray();return listArray;}else if(inComment){if((chrctr==="*")&&(str[pos+1]==="/")){inComment=false;pos+=2;pushComponent();continue;}else{pos+=1;continue;}}else if(isSpace(chrctr)){if((str.charAt(pos-1)&&isSpace(str.charAt(pos-1)))||!component){pos+=1;continue;}else if(parenDepth===0){pushComponent();pos+=1;continue;}else{chrctr=" ";}}else if(chrctr==="("){parenDepth+=1;}else if(chrctr===")"){parenDepth-=1;}else if(chrctr===","){pushComponent();pushComponentArray();pos+=1;continue;}else if((chrctr==="/")&&(str.charAt(pos+1)==="*")){inComment=true;pos+=2;continue;}
component=component+chrctr;pos+=1;}}
function isValidNonNegativeSourceSizeValue(s){if(regexCssLengthWithUnits.test(s)&&(parseFloat(s)>=0)){return true;}
if(regexCssCalc.test(s)){return true;}
if((s==="0")||(s==="-0")||(s==="+0")){return true;}
return false;}
unparsedSizesList=parseComponentValues(strValue);unparsedSizesListLength=unparsedSizesList.length;for(i=0;i<unparsedSizesListLength;i++){unparsedSize=unparsedSizesList[i];lastComponentValue=unparsedSize[unparsedSize.length-1];if(isValidNonNegativeSourceSizeValue(lastComponentValue)){size=lastComponentValue;unparsedSize.pop();}else{continue;}
if(unparsedSize.length===0){return size;}
unparsedSize=unparsedSize.join(" ");if(!(pf.matchesMedia(unparsedSize))){continue;}
return size;}
return"100vw";}
pf.ns=("pf"+new Date().getTime()).substr(0,9);pf.supSrcset="srcset"in image;pf.supSizes="sizes"in image;pf.supPicture=!!window.HTMLPictureElement;if(pf.supSrcset&&pf.supPicture&&!pf.supSizes){(function(image2){image.srcset="data:,a";image2.src="data:,a";pf.supSrcset=image.complete===image2.complete;pf.supPicture=pf.supSrcset&&pf.supPicture;})(document.createElement("img"));}
if(pf.supSrcset&&!pf.supSizes){(function(){var width2="data:image/gif;base64,R0lGODlhAgABAPAAAP///wAAACH5BAAAAAAALAAAAAACAAEAAAICBAoAOw==";var width1="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";var img=document.createElement("img");var test=function(){var width=img.width;if(width===2){pf.supSizes=true;}
alwaysCheckWDescriptor=pf.supSrcset&&!pf.supSizes;isSupportTestReady=true;setTimeout(picturefill);};img.onload=test;img.onerror=test;img.setAttribute("sizes","9px");img.srcset=width1+" 1w,"+width2+" 9w";img.src=width1;})();}else{isSupportTestReady=true;}
pf.selShort="picture>img,img[srcset]";pf.sel=pf.selShort;pf.cfg=cfg;pf.DPR=(DPR||1);pf.u=units;pf.types=types;pf.setSize=noop;pf.makeUrl=memoize(function(src){anchor.href=src;return anchor.href;});pf.qsa=function(context,sel){return("querySelector"in context)?context.querySelectorAll(sel):[];};pf.matchesMedia=function(){if(window.matchMedia&&(matchMedia("(min-width: 0.1em)")||{}).matches){pf.matchesMedia=function(media){return!media||(matchMedia(media).matches);};}else{pf.matchesMedia=pf.mMQ;}
return pf.matchesMedia.apply(this,arguments);};pf.mMQ=function(media){return media?evalCSS(media):true;};pf.calcLength=function(sourceSizeValue){var value=evalCSS(sourceSizeValue,true)||false;if(value<0){value=false;}
return value;};pf.supportsType=function(type){return(type)?types[type]:true;};pf.parseSize=memoize(function(sourceSizeStr){var match=(sourceSizeStr||"").match(regSize);return{media:match&&match[1],length:match&&match[2]};});pf.parseSet=function(set){if(!set.cands){set.cands=parseSrcset(set.srcset,set);}
return set.cands;};pf.getEmValue=function(){var body;if(!eminpx&&(body=document.body)){var div=document.createElement("div"),originalHTMLCSS=docElem.style.cssText,originalBodyCSS=body.style.cssText;div.style.cssText=baseStyle;docElem.style.cssText=fsCss;body.style.cssText=fsCss;body.appendChild(div);eminpx=div.offsetWidth;body.removeChild(div);eminpx=parseFloat(eminpx,10);docElem.style.cssText=originalHTMLCSS;body.style.cssText=originalBodyCSS;}
return eminpx||16;};pf.calcListLength=function(sourceSizeListStr){if(!(sourceSizeListStr in sizeLengthCache)||cfg.uT){var winningLength=pf.calcLength(parseSizes(sourceSizeListStr));sizeLengthCache[sourceSizeListStr]=!winningLength?units.width:winningLength;}
return sizeLengthCache[sourceSizeListStr];};pf.setRes=function(set){var candidates;if(set){candidates=pf.parseSet(set);for(var i=0,len=candidates.length;i<len;i++){setResolution(candidates[i],set.sizes);}}
return candidates;};pf.setRes.res=setResolution;pf.applySetCandidate=function(candidates,img){if(!candidates.length){return;}
var candidate,i,j,length,bestCandidate,curSrc,curCan,candidateSrc,abortCurSrc;var imageData=img[pf.ns];var dpr=pf.DPR;curSrc=imageData.curSrc||img[curSrcProp];curCan=imageData.curCan||setSrcToCur(img,curSrc,candidates[0].set);if(curCan&&curCan.set===candidates[0].set){abortCurSrc=(supportAbort&&!img.complete&&curCan.res-0.1>dpr);if(!abortCurSrc){curCan.cached=true;if(curCan.res>=dpr){bestCandidate=curCan;}}}
if(!bestCandidate){candidates.sort(ascendingSort);length=candidates.length;bestCandidate=candidates[length-1];for(i=0;i<length;i++){candidate=candidates[i];if(candidate.res>=dpr){j=i-1;if(candidates[j]&&(abortCurSrc||curSrc!==pf.makeUrl(candidate.url))&&chooseLowRes(candidates[j].res,candidate.res,dpr,candidates[j].cached)){bestCandidate=candidates[j];}else{bestCandidate=candidate;}
break;}}}
if(bestCandidate){candidateSrc=pf.makeUrl(bestCandidate.url);imageData.curSrc=candidateSrc;imageData.curCan=bestCandidate;if(candidateSrc!==curSrc){pf.setSrc(img,bestCandidate);}
pf.setSize(img);}};pf.setSrc=function(img,bestCandidate){var origWidth;img.src=bestCandidate.url;if(bestCandidate.set.type==="image/svg+xml"){origWidth=img.style.width;img.style.width=(img.offsetWidth+1)+"px";if(img.offsetWidth+1){img.style.width=origWidth;}}};pf.getSet=function(img){var i,set,supportsType;var match=false;var sets=img[pf.ns].sets;for(i=0;i<sets.length&&!match;i++){set=sets[i];if(!set.srcset||!pf.matchesMedia(set.media)||!(supportsType=pf.supportsType(set.type))){continue;}
if(supportsType==="pending"){set=supportsType;}
match=set;break;}
return match;};pf.parseSets=function(element,parent,options){var srcsetAttribute,imageSet,isWDescripor,srcsetParsed;var hasPicture=parent&&parent.nodeName.toUpperCase()==="PICTURE";var imageData=element[pf.ns];if(imageData.src===undefined||options.src){imageData.src=getImgAttr.call(element,"src");if(imageData.src){setImgAttr.call(element,srcAttr,imageData.src);}else{removeImgAttr.call(element,srcAttr);}}
if(imageData.srcset===undefined||options.srcset||!pf.supSrcset||element.srcset){srcsetAttribute=getImgAttr.call(element,"srcset");imageData.srcset=srcsetAttribute;srcsetParsed=true;}
imageData.sets=[];if(hasPicture){imageData.pic=true;getAllSourceElements(parent,imageData.sets);}
if(imageData.srcset){imageSet={srcset:imageData.srcset,sizes:getImgAttr.call(element,"sizes")};imageData.sets.push(imageSet);isWDescripor=(alwaysCheckWDescriptor||imageData.src)&&regWDesc.test(imageData.srcset||"");if(!isWDescripor&&imageData.src&&!getCandidateForSrc(imageData.src,imageSet)&&!imageSet.has1x){imageSet.srcset+=", "+imageData.src;imageSet.cands.push({url:imageData.src,d:1,set:imageSet});}}else if(imageData.src){imageData.sets.push({srcset:imageData.src,sizes:null});}
imageData.curCan=null;imageData.curSrc=undefined;imageData.supported=!(hasPicture||(imageSet&&!pf.supSrcset)||(isWDescripor&&!pf.supSizes));if(srcsetParsed&&pf.supSrcset&&!imageData.supported){if(srcsetAttribute){setImgAttr.call(element,srcsetAttr,srcsetAttribute);element.srcset="";}else{removeImgAttr.call(element,srcsetAttr);}}
if(imageData.supported&&!imageData.srcset&&((!imageData.src&&element.src)||element.src!==pf.makeUrl(imageData.src))){if(imageData.src===null){element.removeAttribute("src");}else{element.src=imageData.src;}}
imageData.parsed=true;};pf.fillImg=function(element,options){var imageData;var extreme=options.reselect||options.reevaluate;if(!element[pf.ns]){element[pf.ns]={};}
imageData=element[pf.ns];if(!extreme&&imageData.evaled===evalId){return;}
if(!imageData.parsed||options.reevaluate){pf.parseSets(element,element.parentNode,options);}
if(!imageData.supported){applyBestCandidate(element);}else{imageData.evaled=evalId;}};pf.setupRun=function(){if(!alreadyRun||isVwDirty||(DPR!==window.devicePixelRatio)){updateMetrics();}};if(pf.supPicture){picturefill=noop;pf.fillImg=noop;}else{(function(){var isDomReady;var regReady=window.attachEvent?/d$|^c/:/d$|^c|^i/;var run=function(){var readyState=document.readyState||"";timerId=setTimeout(run,readyState==="loading"?200:999);if(document.body){pf.fillImgs();isDomReady=isDomReady||regReady.test(readyState);if(isDomReady){clearTimeout(timerId);}}};var timerId=setTimeout(run,document.body?9:99);var debounce=function(func,wait){var timeout,timestamp;var later=function(){var last=(new Date())-timestamp;if(last<wait){timeout=setTimeout(later,wait-last);}else{timeout=null;func();}};return function(){timestamp=new Date();if(!timeout){timeout=setTimeout(later,wait);}};};var lastClientWidth=docElem.clientHeight;var onResize=function(){isVwDirty=Math.max(window.innerWidth||0,docElem.clientWidth)!==units.width||docElem.clientHeight!==lastClientWidth;lastClientWidth=docElem.clientHeight;if(isVwDirty){pf.fillImgs();}};on(window,"resize",debounce(onResize,99));on(document,"readystatechange",run);})();}
pf.picturefill=picturefill;pf.fillImgs=picturefill;pf.teardownRun=noop;picturefill._=pf;window.picturefillCFG={pf:pf,push:function(args){var name=args.shift();if(typeof pf[name]==="function"){pf[name].apply(pf,args);}else{cfg[name]=args[0];if(alreadyRun){pf.fillImgs({reselect:true});}}}};while(setOptions&&setOptions.length){window.picturefillCFG.push(setOptions.shift());}
window.picturefill=picturefill;if(typeof module==="object"&&typeof module.exports==="object"){module.exports=picturefill;}else if(true){!(__WEBPACK_AMD_DEFINE_RESULT__=function(){return picturefill;}.call(exports,__webpack_require__,exports,module),__WEBPACK_AMD_DEFINE_RESULT__!==undefined&&(module.exports=__WEBPACK_AMD_DEFINE_RESULT__));}
if(!pf.supPicture){types["image/webp"]=detectTypeSupport("image/webp","data:image/webp;base64,UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAABBxAR/Q9ERP8DAABWUDggGAAAADABAJ0BKgEAAQADADQlpAADcAD++/1QAA==");}})(window,document);},function(module,exports){(function(window,factory){var lazySizes=factory(window,window.document);window.lazySizes=lazySizes;if(typeof module=='object'&&module.exports){module.exports=lazySizes;}}(window,function l(window,document){'use strict';if(!document.getElementsByClassName){return;}
var lazySizesConfig;var docElem=document.documentElement;var Date=window.Date;var supportPicture=window.HTMLPictureElement;var _addEventListener='addEventListener';var _getAttribute='getAttribute';var addEventListener=window[_addEventListener];var setTimeout=window.setTimeout;var requestAnimationFrame=window.requestAnimationFrame||setTimeout;var requestIdleCallback=window.requestIdleCallback;var regPicture=/^picture$/i;var loadEvents=['load','error','lazyincluded','_lazyloaded'];var regClassCache={};var forEach=Array.prototype.forEach;var hasClass=function(ele,cls){if(!regClassCache[cls]){regClassCache[cls]=new RegExp('(\\s|^)'+cls+'(\\s|$)');}
return regClassCache[cls].test(ele[_getAttribute]('class')||'')&&regClassCache[cls];};var addClass=function(ele,cls){if(!hasClass(ele,cls)){ele.setAttribute('class',(ele[_getAttribute]('class')||'').trim()+' '+cls);}};var removeClass=function(ele,cls){var reg;if((reg=hasClass(ele,cls))){ele.setAttribute('class',(ele[_getAttribute]('class')||'').replace(reg,' '));}};var addRemoveLoadEvents=function(dom,fn,add){var action=add?_addEventListener:'removeEventListener';if(add){addRemoveLoadEvents(dom,fn);}
loadEvents.forEach(function(evt){dom[action](evt,fn);});};var triggerEvent=function(elem,name,detail,noBubbles,noCancelable){var event=document.createEvent('CustomEvent');event.initCustomEvent(name,!noBubbles,!noCancelable,detail||{});elem.dispatchEvent(event);return event;};var updatePolyfill=function(el,full){var polyfill;if(!supportPicture&&(polyfill=(window.picturefill||lazySizesConfig.pf))){polyfill({reevaluate:true,elements:[el]});}else if(full&&full.src){el.src=full.src;}};var getCSS=function(elem,style){return(getComputedStyle(elem,null)||{})[style];};var getWidth=function(elem,parent,width){width=width||elem.offsetWidth;while(width<lazySizesConfig.minSize&&parent&&!elem._lazysizesWidth){width=parent.offsetWidth;parent=parent.parentNode;}
return width;};var rAF=(function(){var running,waiting;var fns=[];var run=function(){var fn;running=true;waiting=false;while(fns.length){fn=fns.shift();fn[0].apply(fn[1],fn[2]);}
running=false;};return function(fn){if(running){fn.apply(this,arguments);}else{fns.push([fn,this,arguments]);if(!waiting){waiting=true;(document.hidden?setTimeout:requestAnimationFrame)(run);}}};})();var rAFIt=function(fn,simple){return simple?function(){rAF(fn);}:function(){var that=this;var args=arguments;rAF(function(){fn.apply(that,args);});};};var throttle=function(fn){var running;var lastTime=0;var gDelay=125;var RIC_DEFAULT_TIMEOUT=999;var rICTimeout=RIC_DEFAULT_TIMEOUT;var run=function(){running=false;lastTime=Date.now();fn();};var idleCallback=requestIdleCallback?function(){requestIdleCallback(run,{timeout:rICTimeout});if(rICTimeout!==RIC_DEFAULT_TIMEOUT){rICTimeout=RIC_DEFAULT_TIMEOUT;}}:rAFIt(function(){setTimeout(run);},true);return function(isPriority){var delay;if((isPriority=isPriority===true)){rICTimeout=66;}
if(running){return;}
running=true;delay=gDelay-(Date.now()-lastTime);if(delay<0){delay=0;}
if(isPriority||(delay<9&&requestIdleCallback)){idleCallback();}else{setTimeout(idleCallback,delay);}};};var debounce=function(func){var timeout,timestamp;var wait=99;var run=function(){timeout=null;func();};var later=function(){var last=Date.now()-timestamp;if(last<wait){setTimeout(later,wait-last);}else{(requestIdleCallback||run)(run);}};return function(){timestamp=Date.now();if(!timeout){timeout=setTimeout(later,wait);}};};var loader=(function(){var lazyloadElems,preloadElems,isCompleted,resetPreloadingTimer,loadMode,started;var eLvW,elvH,eLtop,eLleft,eLright,eLbottom;var defaultExpand,preloadExpand,hFac;var regImg=/^img$/i;var regIframe=/^iframe$/i;var supportScroll=('onscroll'in window)&&!(/glebot/.test(navigator.userAgent));var shrinkExpand=0;var currentExpand=0;var isLoading=0;var lowRuns=0;var resetPreloading=function(e){isLoading--;if(e&&e.target){addRemoveLoadEvents(e.target,resetPreloading);}
if(!e||isLoading<0||!e.target){isLoading=0;}};var isNestedVisible=function(elem,elemExpand){var outerRect;var parent=elem;var visible=getCSS(document.body,'visibility')=='hidden'||getCSS(elem,'visibility')!='hidden';eLtop-=elemExpand;eLbottom+=elemExpand;eLleft-=elemExpand;eLright+=elemExpand;while(visible&&(parent=parent.offsetParent)&&parent!=document.body&&parent!=docElem){visible=((getCSS(parent,'opacity')||1)>0);if(visible&&getCSS(parent,'overflow')!='visible'){outerRect=parent.getBoundingClientRect();visible=eLright>outerRect.left&&eLleft<outerRect.right&&eLbottom>outerRect.top-1&&eLtop<outerRect.bottom+1;}}
return visible;};var checkElements=function(){var eLlen,i,rect,autoLoadElem,loadedSomething,elemExpand,elemNegativeExpand,elemExpandVal,beforeExpandVal;if((loadMode=lazySizesConfig.loadMode)&&isLoading<8&&(eLlen=lazyloadElems.length)){i=0;lowRuns++;if(preloadExpand==null){if(!('expand'in lazySizesConfig)){lazySizesConfig.expand=docElem.clientHeight>500?500:400;}
defaultExpand=lazySizesConfig.expand;preloadExpand=defaultExpand*lazySizesConfig.expFactor;}
if(currentExpand<preloadExpand&&isLoading<1&&lowRuns>3&&loadMode>2){currentExpand=preloadExpand;lowRuns=0;}else if(loadMode>1&&lowRuns>2&&isLoading<6){currentExpand=defaultExpand;}else{currentExpand=shrinkExpand;}
for(;i<eLlen;i++){if(!lazyloadElems[i]||lazyloadElems[i]._lazyRace){continue;}
if(!supportScroll){unveilElement(lazyloadElems[i]);continue;}
if(!(elemExpandVal=lazyloadElems[i][_getAttribute]('data-expand'))||!(elemExpand=elemExpandVal*1)){elemExpand=currentExpand;}
if(beforeExpandVal!==elemExpand){eLvW=innerWidth+(elemExpand*hFac);elvH=innerHeight+elemExpand;elemNegativeExpand=elemExpand*-1;beforeExpandVal=elemExpand;}
rect=lazyloadElems[i].getBoundingClientRect();if((eLbottom=rect.bottom)>=elemNegativeExpand&&(eLtop=rect.top)<=elvH&&(eLright=rect.right)>=elemNegativeExpand*hFac&&(eLleft=rect.left)<=eLvW&&(eLbottom||eLright||eLleft||eLtop)&&((isCompleted&&isLoading<3&&!elemExpandVal&&(loadMode<3||lowRuns<4))||isNestedVisible(lazyloadElems[i],elemExpand))){unveilElement(lazyloadElems[i]);loadedSomething=true;if(isLoading>9){break;}}else if(!loadedSomething&&isCompleted&&!autoLoadElem&&isLoading<4&&lowRuns<4&&loadMode>2&&(preloadElems[0]||lazySizesConfig.preloadAfterLoad)&&(preloadElems[0]||(!elemExpandVal&&((eLbottom||eLright||eLleft||eLtop)||lazyloadElems[i][_getAttribute](lazySizesConfig.sizesAttr)!='auto')))){autoLoadElem=preloadElems[0]||lazyloadElems[i];}}
if(autoLoadElem&&!loadedSomething){unveilElement(autoLoadElem);}}};var throttledCheckElements=throttle(checkElements);var switchLoadingClass=function(e){addClass(e.target,lazySizesConfig.loadedClass);removeClass(e.target,lazySizesConfig.loadingClass);addRemoveLoadEvents(e.target,rafSwitchLoadingClass);};var rafedSwitchLoadingClass=rAFIt(switchLoadingClass);var rafSwitchLoadingClass=function(e){rafedSwitchLoadingClass({target:e.target});};var changeIframeSrc=function(elem,src){try{elem.contentWindow.location.replace(src);}catch(e){elem.src=src;}};var handleSources=function(source){var customMedia,parent;var sourceSrcset=source[_getAttribute](lazySizesConfig.srcsetAttr);if((customMedia=lazySizesConfig.customMedia[source[_getAttribute]('data-media')||source[_getAttribute]('media')])){source.setAttribute('media',customMedia);}
if(sourceSrcset){source.setAttribute('srcset',sourceSrcset);}
if(customMedia){parent=source.parentNode;parent.insertBefore(source.cloneNode(),source);parent.removeChild(source);}};var lazyUnveil=rAFIt(function(elem,detail,isAuto,sizes,isImg){var src,srcset,parent,isPicture,event,firesLoad;if(!(event=triggerEvent(elem,'lazybeforeunveil',detail)).defaultPrevented){if(sizes){if(isAuto){addClass(elem,lazySizesConfig.autosizesClass);}else{elem.setAttribute('sizes',sizes);}}
srcset=elem[_getAttribute](lazySizesConfig.srcsetAttr);src=elem[_getAttribute](lazySizesConfig.srcAttr);if(isImg){parent=elem.parentNode;isPicture=parent&&regPicture.test(parent.nodeName||'');}
firesLoad=detail.firesLoad||(('src'in elem)&&(srcset||src||isPicture));event={target:elem};if(firesLoad){addRemoveLoadEvents(elem,resetPreloading,true);clearTimeout(resetPreloadingTimer);resetPreloadingTimer=setTimeout(resetPreloading,2500);addClass(elem,lazySizesConfig.loadingClass);addRemoveLoadEvents(elem,rafSwitchLoadingClass,true);}
if(isPicture){forEach.call(parent.getElementsByTagName('source'),handleSources);}
if(srcset){elem.setAttribute('srcset',srcset);}else if(src&&!isPicture){if(regIframe.test(elem.nodeName)){changeIframeSrc(elem,src);}else{elem.src=src;}}
if(srcset||isPicture){updatePolyfill(elem,{src:src});}}
rAF(function(){if(elem._lazyRace){delete elem._lazyRace;}
removeClass(elem,lazySizesConfig.lazyClass);if(!firesLoad||elem.complete){if(firesLoad){resetPreloading(event);}else{isLoading--;}
switchLoadingClass(event);}});});var unveilElement=function(elem){var detail;var isImg=regImg.test(elem.nodeName);var sizes=isImg&&(elem[_getAttribute](lazySizesConfig.sizesAttr)||elem[_getAttribute]('sizes'));var isAuto=sizes=='auto';if((isAuto||!isCompleted)&&isImg&&(elem.src||elem.srcset)&&!elem.complete&&!hasClass(elem,lazySizesConfig.errorClass)){return;}
detail=triggerEvent(elem,'lazyunveilread').detail;if(isAuto){autoSizer.updateElem(elem,true,elem.offsetWidth);}
elem._lazyRace=true;isLoading++;lazyUnveil(elem,detail,isAuto,sizes,isImg);};var onload=function(){if(isCompleted){return;}
if(Date.now()-started<999){setTimeout(onload,999);return;}
var afterScroll=debounce(function(){lazySizesConfig.loadMode=3;throttledCheckElements();});isCompleted=true;lazySizesConfig.loadMode=3;throttledCheckElements();addEventListener('scroll',function(){if(lazySizesConfig.loadMode==3){lazySizesConfig.loadMode=2;}
afterScroll();},true);};return{_:function(){started=Date.now();lazyloadElems=document.getElementsByClassName(lazySizesConfig.lazyClass);preloadElems=document.getElementsByClassName(lazySizesConfig.lazyClass+' '+lazySizesConfig.preloadClass);hFac=lazySizesConfig.hFac;addEventListener('scroll',throttledCheckElements,true);addEventListener('resize',throttledCheckElements,true);if(window.MutationObserver){new MutationObserver(throttledCheckElements).observe(docElem,{childList:true,subtree:true,attributes:true});}else{docElem[_addEventListener]('DOMNodeInserted',throttledCheckElements,true);docElem[_addEventListener]('DOMAttrModified',throttledCheckElements,true);setInterval(throttledCheckElements,999);}
addEventListener('hashchange',throttledCheckElements,true);['focus','mouseover','click','load','transitionend','animationend','webkitAnimationEnd'].forEach(function(name){document[_addEventListener](name,throttledCheckElements,true);});if((/d$|^c/.test(document.readyState))){onload();}else{addEventListener('load',onload);document[_addEventListener]('DOMContentLoaded',throttledCheckElements);setTimeout(onload,20000);}
throttledCheckElements(lazyloadElems.length>0);},checkElems:throttledCheckElements,unveil:unveilElement};})();var autoSizer=(function(){var autosizesElems;var sizeElement=rAFIt(function(elem,parent,event,width){var sources,i,len;elem._lazysizesWidth=width;width+='px';elem.setAttribute('sizes',width);if(regPicture.test(parent.nodeName||'')){sources=parent.getElementsByTagName('source');for(i=0,len=sources.length;i<len;i++){sources[i].setAttribute('sizes',width);}}
if(!event.detail.dataAttr){updatePolyfill(elem,event.detail);}});var getSizeElement=function(elem,dataAttr,width){var event;var parent=elem.parentNode;if(parent){width=getWidth(elem,parent,width);event=triggerEvent(elem,'lazybeforesizes',{width:width,dataAttr:!!dataAttr});if(!event.defaultPrevented){width=event.detail.width;if(width&&width!==elem._lazysizesWidth){sizeElement(elem,parent,event,width);}}}};var updateElementsSizes=function(){var i;var len=autosizesElems.length;if(len){i=0;for(;i<len;i++){getSizeElement(autosizesElems[i]);}}};var debouncedUpdateElementsSizes=debounce(updateElementsSizes);return{_:function(){autosizesElems=document.getElementsByClassName(lazySizesConfig.autosizesClass);addEventListener('resize',debouncedUpdateElementsSizes);},checkElems:debouncedUpdateElementsSizes,updateElem:getSizeElement};})();var init=function(){if(!init.i){init.i=true;autoSizer._();loader._();}};(function(){var prop;var lazySizesDefaults={lazyClass:'lazyload',loadedClass:'lazyloaded',loadingClass:'lazyloading',preloadClass:'lazypreload',errorClass:'lazyerror',autosizesClass:'lazyautosizes',srcAttr:'data-src',srcsetAttr:'data-srcset',sizesAttr:'data-sizes',minSize:40,customMedia:{},init:true,expFactor:1.5,hFac:0.8,loadMode:2};lazySizesConfig=window.lazySizesConfig||window.lazysizesConfig||{};for(prop in lazySizesDefaults){if(!(prop in lazySizesConfig)){lazySizesConfig[prop]=lazySizesDefaults[prop];}}
window.lazySizesConfig=lazySizesConfig;setTimeout(function(){if(lazySizesConfig.init){init();}});})();return{cfg:lazySizesConfig,autoSizer:autoSizer,loader:loader,init:init,uP:updatePolyfill,aC:addClass,rC:removeClass,hC:hasClass,fire:triggerEvent,gW:getWidth,rAF:rAF,};}));}]);